# Generated by Django 5.1 on 2024-10-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_equipment_image_room_image_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
    ]
