# Generated by Django 5.1 on 2024-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_equipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(default='image.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
